// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	user "main.go/internal/user"
)

// UserCreator is an autogenerated mock type for the UserCreator type
type UserCreator struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: u
func (_m *UserCreator) CreateUser(u *user.User) int {
	ret := _m.Called(u)

	var r0 int
	if rf, ok := ret.Get(0).(func(*user.User) int); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewUserCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserCreator creates a new instance of UserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserCreator(t mockConstructorTestingTNewUserCreator) *UserCreator {
	mock := &UserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
